all:
	cp entry*.ewd         ~/www/ewd/GrowthChartsMCM
	cp *Chart.ewd         ~/www/ewd/GrowthChartsMCM
	cp *Page.ewd          ~/www/ewd/GrowthChartsMCM
	cp addNewPrtp.ewd     ~/www/ewd/GrowthChartsMCM
	cp adminPage.ewd      ~/www/ewd/GrowthChartsMCM
	cp newPrtRedirect.ewd ~/www/ewd/GrowthChartsMCM
	cp login*.ewd         ~/www/ewd/GrowthChartsMCM
	cp entry*.m           ~/www/r
	cp growthChartsMCM.m  ~/www/r
	cp newParticipant.m   ~/www/r
	cp Admin.m            ~/www/r
	cp *.png              ~/www/resources
	${gtm_dist}/mumps -r make^zluis

