all:
	cp entry*.ewd ~/www/ewd/GrowthChartsMCM
	cp *Chart.ewd ~/www/ewd/GrowthChartsMCM
	cp entry*.m           ~/www/r
	cp growthChartsMCM.m  ~/www/r
	cp *.png              ~/www/resources
	${gtm_dist}/mumps -r make^zluis

